name: Build step


on:
  push:
    branches: 
     - main
  pull_request:
    branches: [ "main" ]


jobs:

     
   build-and-push-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME}}
          password:  ${{ secrets.DOCKER_PASSWORD }}
     
          
      - name: Build image and push to Docker Hub 
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: |
            ikbelkhemiri/frontend:${{ github.sha }}
          push: true
